CREATE DATABASE shop-service;

INSERT INTO roles(id , name) VALUES(1, 'ROLE_USER');
INSERT INTO roles(id , name) VALUES(2, 'ROLE_SUPER_ADMINISTRATOR');
INSERT INTO roles(id , name) VALUES(3, 'ROLE_ADMINISTRATOR');